# Generated by Django 5.0.6 on 2024-05-12 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'GitHub'), (2, 'Twitter'), (3, 'LinkedIn'), (4, 'Youtube'), (5, 'Facebook'), (6, 'Twitch'), (7, 'Dev.to'), (8, 'Codewars'), (9, 'Codepen'), (10, 'FreeCodeCamp'), (11, 'GitLab'), (12, 'Hashnode'), (13, 'Stack Overflow')])),
                ('link_address', models.URLField()),
                ('position', models.IntegerField(default=1, help_text='Position of the link in the list,start with 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
